### ISSUE TITLE
Clarification(Testimonials page): Clarify me which page style need follow bcoz there is no information about 'Testimonials page' In project scope and also design brief.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/West-Coast-Sheet-Metal#10]
And also there is no psd.

**Comment by ankittitan** [comment]
The sample of Testimonial page is attached to Website Build task by PM Bill
https://projects.titanweb.com.au/public/index.php?path_info=projects/west-coast-sheet-metal-pack2responsivere/tasks/26
