### ISSUE TITLE
Contact us: Message field and the map aren't aligned.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/West-Coast-Sheet-Metal#104]
![image](https://cloud.githubusercontent.com/assets/11186313/12970391/4eb3f07c-d0c9-11e5-86bd-d9499ebff534.png)

**Comment by ankittitan** [comment]
Hi,
Since the address is large the map is not aligned with message field, if we aligned both in a line the address will overlap on the map or the space between input fields will vary.
Thanks

**Comment by roseliesromeo** [comment]
Extend the address to occupy up to the edge of the map.

![image](https://cloud.githubusercontent.com/assets/11186313/13066620/fe9ccb58-d4a2-11e5-82af-9ba24216f795.png)
