### ISSUE TITLE
Home - what we do: Read more link is disrupted in iPad air (landscape view).

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/West-Coast-Sheet-Metal#114]
![image](https://cloud.githubusercontent.com/assets/11186313/13069053/035881aa-d4bc-11e5-9e2b-3905792f5066.png)

**Comment by ankittitan** [comment]
Working fine in i pad air 
![img_1159](https://cloud.githubusercontent.com/assets/14210977/13100307/b666c3ec-d561-11e5-8cf5-2b1f298e070c.PNG)
![img_1160](https://cloud.githubusercontent.com/assets/14210977/13100308/b98bd288-d561-11e5-95d4-de8106a007fd.PNG)
