### ISSUE TITLE
Gallery page: Breadcrumbs are missing and doesn't have the same layout and style with the other single pages.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/West-Coast-Sheet-Metal#43]
![2015-12-16_1733-gg](https://cloud.githubusercontent.com/assets/13309730/11840363/54000942-a41b-11e5-93ff-f18da61b357e.png)

**Comment by mahender-sowedane** [comment]
Not fixed

**Comment by ankittitan** [comment]
this is a ngg plugin issue.

**Comment by mahender-sowedane** [comment]
After discussion with my TL, still it's an issue.
Your managed to make it work in the above album, it should also work for newly added album's.
thanks!

**Comment by mahender-sowedane** [comment]
Not fixed

![2016-01-22_2000gallery](https://cloud.githubusercontent.com/assets/13309730/12544601/c0f82fce-c361-11e5-87f0-3afc4d525e06.png)

**Comment by mahender-sowedane** [comment]
Not fixed

![2016-02-04_1113](https://cloud.githubusercontent.com/assets/13309730/12806917/68893ca8-cb30-11e5-9f79-1e52e603bd88.png)

**Comment by mahender-sowedane** [comment]
Not fixed

![2016-02-09_1032-brdcrm](https://cloud.githubusercontent.com/assets/13309730/12908044/a308fb02-cf18-11e5-847c-1c8a5fd2d369.png)
