### ISSUE TITLE
Contact Us-Mobile: Email field value was displayed on the second line and almost clipped.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/West-Coast-Sheet-Metal#54]
![img_1168](https://cloud.githubusercontent.com/assets/13309730/12141531/3ff1745a-b496-11e5-86ba-968a4dde4786.PNG)

**Comment by ankittitan** [comment]
Long emails cannot be fit into single line.

**Comment by mahender-sowedane** [comment]
It's not a long email and also observe there is a space for right side to utilize it
thanks!

**Comment by ankittitan** [comment]
the right side width will be occupied by address and postal address, we cannot enlarge email width..

**Comment by mahender-sowedane** [comment]
It's not good for look and feel purpose, Discuss with your TL and fix it properly
thanks!

**Comment by ankittitan** [comment]
Discussed with TL, it is not a bug

**Comment by mahender-sowedane** [comment]
It should display the contact details in one column in that resolution.
Resolve the issue properly.
thanks!

**Comment by ankittitan** [comment]
How can we adjust longer emails in one line? Technically it is not possible.
