### ISSUE TITLE
Testimonials: The page should display the entire description of a testimonial custom post

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/West-Coast-Sheet-Metal#55]
![untitled-133](https://cloud.githubusercontent.com/assets/13309730/12142273/d077a62e-b49c-11e5-9c72-54a6e25414a8.png)

**Comment by ankittitan** [comment]
As per psd the content is restricted to 9 lines only, and we followed it.
Title is clickable and it will display complete content on single page

**Comment by mahender-sowedane** [comment]
It doesn't mentioned in project scope to link single page, should be display entire content
thanks!
