### ISSUE TITLE
Home page(Gmap: Pre-footer section): Search button wasn't implemented.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/West-Coast-Sheet-Metal#8]
![untitled-2](https://cloud.githubusercontent.com/assets/13309730/11804375/55a4d46e-a329-11e5-869a-7cdb30122fa1.png)

**Comment by mahender-sowedane** [comment]
Still not fixed

**Comment by mahender-sowedane** [comment]
Give me an explanation why won't fix it.
thanks!

**Comment by ankittitan** [comment]
We have to talk to Jolene in this regard.

**Comment by mahender-sowedane** [comment]
We're not closing this issue until we have an answer

**Comment by ankittitan** [comment]
Awaiting reply from Project Manager.

**Comment by ankittitan** [comment]
I think this is only a google map screenshot that the designer used, and not a required search functionality, please look the mail replied by Jolene for this.
