### ISSUE TITLE
FAQ page: Post titles are not displaying completely, Currently limited to single line. 

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/West-Coast-Sheet-Metal#9]
![untitled-3](https://cloud.githubusercontent.com/assets/13309730/11804595/0dbb09be-a32b-11e5-9375-2d9db204ea0e.png)

**Comment by ankittitan** [comment]
As per PSD post title should be of only one line.

**Comment by mahender-sowedane** [comment]
it should still display all text as it's not restricted by the design.

**Comment by ankittitan** [comment]
How can we display four line title in single line ?

**Comment by mahender-sowedane** [comment]
Not fixed, Discuss with your TL and fix it properly.
Thanks!

**Comment by ankittitan** [comment]
Discussed with TL it is not a bug..

**Comment by mahender-sowedane** [comment]
I already discussed with QA Team lead, fix it properly
thanks!
