### ISSUE TITLE
Home: Bullet marks aren't displayed in the listed content.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/West-Coast-Sheet-Metal#93]
Applicable to Contact us page.
![image](https://cloud.githubusercontent.com/assets/11186313/12940620/f976d160-d005-11e5-9db4-64d0632a9678.png)

**Comment by roseliesromeo** [comment]
Not fixed.
![image](https://cloud.githubusercontent.com/assets/11186313/13067862/184cf7fa-d4b0-11e5-90dd-8001942e01dd.png)

**Comment by ankittitan** [comment]
It is working fine.
![bullets](https://cloud.githubusercontent.com/assets/14210977/13077142/fcb294b4-d4dc-11e5-85c9-91503e2046d9.png)
